#!/usr/bin/env bash

sHost=$(hostname -s)
sMessage="mail test from [$sHost] at [$(date)]"
sFrom="root-$sHost <root>"

#info@maxromanov.com; info@wrapapa.com; info@revolab.net; info@nethlo.com; info@cc45.cc

#sTo="spam@z.maxromanov.com."
#sTo="info@cc45.cc."
sTo="max@maxromanov.com."
#sTo="root"


printf "To: $sTo\nFrom: $sFrom\nSubject: $sMessage\n\n$sMessage\n" | sendmail -vv -t 2>&1
